import { Router } from 'express';
// import { clinicRoutes } from './clinic.routes';
// import { clinicAddressRoutes } from './clinicaddress.routes';
// import { configPlanRoutes } from './configplan.routes';
// import { customizeRoutes } from './customize.routes';
// import { systemRoutes } from './system.routes';
// import { procedureRoutes } from './procedure.routes';
// import { covenantRoutes } from './covenant.routes';
// import { specialtyRoutes } from './specialty.routes';
// import { professionalRoutes } from './professional.routes';
// import { councilRoutes } from './council.routes';
// import { procedureProfessionalRoutes } from './procedureprofessional.routes';
// import { procedureCovenantRoutes } from './procedurecovenant.routes';
// import { scheduleRoutes } from './schedule.routes';
// import { clientRoutes } from './client.routes';
// import { appointmentRoutes } from './appointment.routes';
// import { bankAccountRoutes } from './bankaccount.routes';
// import { orgUnitRoutes } from './orgunit.routes';
// import { paymentMethodsRoutes } from './paymentmethod.routes';
// import { planAccountRoutes } from './planaccount.routes';
// import { receiverRoutes } from './receiver.routes';
// import { supplierRoutes } from './supplier.routes';
// import { revenueRoutes } from './revenue.routes';
// import { userRoutes } from './user.routes';
// import { userTypeRoutes } from './usertype.routes';
// import { userSessionRoutes } from './usersession.routes';
// import { medicalRecordRoutes } from './medicalrecord.routes';
// import { certificateRoutes } from './certificate.routes';
// import { certificateTypeRoutes } from './certificatetype.routes';
// import { physiotherapyAssessmentRoutes } from './physiotherapyAssessment.routes';
// import { physiotherapyClinicalExamRoutes } from './physiotherapyclinicalexam.routes';
// import { physiotherapyTherapeuticPlanRoutes } from './physiotherapytherapeuticplan.routes';
// import { clientHistoryRoutes } from './clienthistory.routes';
// import { clinicHistoryRoutes } from './clinichistory.routes';
// import { familyHistoryRoutes } from './familyhistory.routes';
// import { psicoSocialRoutes } from './psicosocial.routes';
// import { treatmentRoutes } from './treatment.routes';
// import { treatmentReturnRoutes } from './treatmentreturn.routes';
// import { prescriptionRoutes } from './prescription.routes';
// import { examRoutes } from './exam.routes';
// import { imcRoutes } from './imc.routes';
// import { expenseRoutes } from './expense.routes';
// import { userProfessionalRoutes } from './userprofessional.routes';
// import { userProfessionalClinicRoutes } from './userprofessionalclinic.routes';
// import { userProfessionalSessionRoutes } from './userprofessionalsession.routes';
// import { transferRoutes } from './transfer.routes';
// import { clientAddressRoutes } from './clientaddress.routes';
// import { dashboardRoutes } from './dashboard.routes';
// import { templateWhatsappRoutes } from './templatewhatsapp.routes';
// import { appointmentProcedureRoutes } from './appointmentprocedure.routes';
// import { bulaRoutes } from './bula.routes';
// import { exctractRoutes } from './extractroutes';
// import { cashFlowRoutes } from './cashflow.routes';
// import { kinshipRoutes } from './kinship.routes';
// import { professionalAddressRoutes } from './professionaladdress.routes';
// import { forgotPasswordRoutes } from './forgotpassword.routes';
// import { resetPasswordRoutes } from './resetpassword.routes';
// import { forgotPasswordProfessionalRoutes } from './forgotpasswordprofessional.routes';
// import { resetPasswordProfessionalRoutes } from './resetpasswordprofessional.routes';
// import { pilatesRoutes } from './pilates.routes';
// import { pilatesEquipmentRoutes } from './pilatesequipment.routes';
// import { pilatesExerciseRoutes } from './pilatesexercise.routes';
// import { pilatesDescriptionRoutes } from './pilatesdescription.routes';
// import { psychologyRoutes } from './psychology.routes';
// import { psychologyPsychicExamRoutes } from './psychologypsychicexam.routes';
// import { psychologyCurrentHistoryRoutes } from './psychologycurrenthistory.routes';
// import { psychologyFamilyHistoryRoutes } from './psychologyfamilyhistory.routes';
// import { psychologyPersonalHistoryRoutes } from './psychologypersonalhistory.routes';
// import { psychologyObservationsRoutes } from './psychologyobservations.routes';
// import { appointmentPaymentRoutes } from './appointmentpayment.routes';
// import { professionalSessionRoutes } from './professionalsession.routes';
// import { ticketRoutes } from './ticket.routes';
// import { ticketCategoryRoutes } from './ticketcategory.routes';
// import { whatsappRoutes } from './whatsapp.routes';
// import { planRoutes } from './plan.routes';

const router = Router();

// router.use('/clinic', clinicRoutes);
// router.use('/clinic-address', clinicAddressRoutes);
// router.use('/clinic-config-plan', configPlanRoutes);
// router.use('/clinic-customize', customizeRoutes);
// router.use('/clinic-system', systemRoutes);
// router.use('/procedure', procedureRoutes);
// router.use('/ticket-category', ticketCategoryRoutes);
// router.use('/ticket', ticketRoutes);
// router.use('/covenant', covenantRoutes);
// router.use('/specialty', specialtyRoutes);
// router.use('/professional', professionalRoutes);
// router.use('/forgot-password-professional', forgotPasswordProfessionalRoutes);
// router.use('/reset-password-professional', resetPasswordProfessionalRoutes);
// router.use('/professional-address', professionalAddressRoutes);
// router.use('/professional-session', professionalSessionRoutes);
// router.use('/council', councilRoutes);
// router.use('/procedure-professional', procedureProfessionalRoutes);
// router.use('/procedure-covenant', procedureCovenantRoutes);
// router.use('/schedule', scheduleRoutes);
// router.use('/client', clientRoutes);
// router.use('/client-address', clientAddressRoutes);
// router.use('/appointment', appointmentRoutes);
// router.use('/appointment-payment', appointmentPaymentRoutes);
// router.use('/bank-account', bankAccountRoutes);
// router.use('/organization-unit', orgUnitRoutes);
// router.use('/payment-method', paymentMethodsRoutes);
// router.use('/plan-account', planAccountRoutes);
// router.use('/plan', planRoutes);
// router.use('/receiver', receiverRoutes);
// router.use('/supplier', supplierRoutes);
// router.use('/revenue', revenueRoutes);
// router.use('/user', userRoutes);
// router.use('/forgot-password-user', forgotPasswordRoutes);
// router.use('/reset-password-user', resetPasswordRoutes);
// router.use('/user-professional', userProfessionalRoutes);
// router.use('/user-professional-clinic', userProfessionalClinicRoutes);
// router.use('/user-type', userTypeRoutes);
// router.use('/user-session', userSessionRoutes);
// router.use('/user-professional-session', userProfessionalSessionRoutes);
// router.use('/medical-record', medicalRecordRoutes);
// router.use('/treatment', treatmentRoutes);
// router.use('/treatment-return', treatmentReturnRoutes);
// router.use('/certificate', certificateRoutes);
// router.use('/certificate-type', certificateTypeRoutes);
// router.use('/prescription', prescriptionRoutes);
// router.use('/physiotherapy-assessment', physiotherapyAssessmentRoutes);
// router.use('/physiotherapy-clinical-exam', physiotherapyClinicalExamRoutes);
// router.use(
//   '/physiotherapy-therapeutic-plan',
//   physiotherapyTherapeuticPlanRoutes,
// );
// router.use('/psychology', psychologyRoutes);
// router.use('/psychology-psychic-exam', psychologyPsychicExamRoutes);
// router.use('/psychology-current-history', psychologyCurrentHistoryRoutes);
// router.use('/psychology-family-history', psychologyFamilyHistoryRoutes);
// router.use('/psychology-personal-history', psychologyPersonalHistoryRoutes);
// router.use('/psychology-observations', psychologyObservationsRoutes);
// router.use('/pilates', pilatesRoutes);
// router.use('/pilates-equipment', pilatesEquipmentRoutes);
// router.use('/pilates-exercise', pilatesExerciseRoutes);
// router.use('/pilates-description', pilatesDescriptionRoutes);
// router.use('/imc', imcRoutes);
// router.use('/history-client', clientHistoryRoutes);
// router.use('/history-clinic', clinicHistoryRoutes);
// router.use('/history-family', familyHistoryRoutes);
// router.use('/psico-social', psicoSocialRoutes);
// router.use('/exam', examRoutes);
// router.use('/expense', expenseRoutes);
// router.use('/transfer', transferRoutes);
// router.use('/exctract', exctractRoutes);
// router.use('/dashboard', dashboardRoutes);
// router.use('/template-whatsapp', templateWhatsappRoutes);
// router.use('/appointment-procedure', appointmentProcedureRoutes);
// router.use('/bula', bulaRoutes);
// router.use('/cash-flow', cashFlowRoutes);
// router.use('/kinship', kinshipRoutes);
// router.use('/whatsapp', whatsappRoutes);
// // router.use('/service-emails-automatic', emailsAutomaticRoutes);

export { router };
